print("="*30)
print(f"---Bienvenido a YoFinanzas---")
print("="*30)
print(" ")
print("¿Que desea hacer?\n")
print(" -1- para menu principal.\n -2- para salir.\n" )
opcion = input(str("Ingrese una opcion para continuar:  ")).strip().lower()
if opcion == "2":
    print("=="*10)
    print("Saliendo...")
    print("=="*10)
